services:
  - type: web
    name: pneumonia-detection
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    buildFilter:
      paths:
        - app.py
        - model_file.py
        - requirements.txt
        - pneumonia.weights.h5
        - static/**
        - templates/**
