services:
  - type: web
    name: pneumonia-detection
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
